export type Shape='ship'|'harbor'|'bridge'|'crane'|'pod'|'container'|'process'|'volume'|'plate'|'ledger';
export type Piece={id:string;name:string;analogy:string;shape:Shape;color:number;description:string;limit:string;scope?:string};
export type Scope={id:string;name:string;parent?:string;pieces:Piece[];relations?:string[]};
const part=(id:string,name:string,analogy:string,shape:Shape,color:number,description:string,limit:string,scope?:string):Piece=>({id,name,analogy,shape,color,description,limit,scope});
const container=(id:string,helper=false)=>part(id,helper?'Helper container':'Application container',helper?'Supporting cargo':'Main cargo','container',helper?0x358f87:0xc76b40,'A separate container image, root filesystem and process within the same Pod.','Two containers in one Pod share the configured network context, not their entire filesystems.',helper?'helper':'app');
export const scopes:Record<string,Scope>={
fleet:{id:'fleet',name:'Fleet',pieces:[part('harbor','Control plane','Harbor administration','harbor',0x7d9ab8,'Independent components coordinate cluster state through the API.','These components also run on computers; the harbor is a visual analogy.','harbor'),part('worker-01','Worker node 01','Reference ship','ship',0x225b80,'One Linux machine runs kubelet, a container runtime and assigned Pods.','The Node API object describes this machine; it is not the machine itself.','node'),part('worker-02','Worker node 02','Context ship','ship',0x298a81,'A second worker can receive independently scheduled Pods.','Detailed inspection currently focuses on worker-01.')]},
node:{id:'node',name:'Worker-01',parent:'fleet',relations:['kubelet → CRI → container runtime','Pod is assigned to worker-01','All processes use the host Linux kernel'],pieces:[part('node-hull','Node structure','Hull and deck','ship',0x225b80,'The host provides CPU, memory, storage and network capacity.','The hull is a model of the machine, not an API object.'),part('kubelet','kubelet','Captain’s bridge','bridge',0x53a39a,'Observes assigned Pods, reconciles execution and reports status.','The local captain does not choose placements for the fleet.'),part('runtime','Container runtime','Loading machinery','crane',0xdba025,'containerd handles runtime operations through CRI and uses an OCI runtime.','Docker Engine is not required. The crane does not represent CNI.','runtime'),part('pod','Reference Pod','Shared cargo unit','pod',0x9bafa3,'This anatomy example contains two regular containers and an explicitly shared volume.','This two-container model is separate from the one-container guided scenario.','pod'),part('linux','Linux foundation','Below deck','plate',0x8d86af,'The shared kernel provides process isolation, resource controls and networking.','Namespaces and cgroups are mechanisms, not physical cargo.','linux')]},
pod:{id:'pod',name:'Reference Pod',parent:'node',relations:['Application container ↔ shared network ↔ helper container','Both containers explicitly mount the same emptyDir volume','Pod API record ↔ runtime sandbox (distinct identities)'],pieces:[part('pod-frame','Pod grouping','Cargo frame','pod',0x9bafa3,'One scheduling unit groups containers and declared shared resources.','The visible frame represents grouping, not a stored API object.'),container('container-app'),container('container-helper',true),part('sandbox','Runtime sandbox','Shared platform','plate',0x718ca4,'The runtime prepares the Pod sandbox for the selected configuration.','Sandbox implementation varies with the runtime.'),part('network','Shared network context','Connection rail','plate',0x478fbc,'In this profile, both containers share the Pod network namespace and port space.','Containers do not each get a separate Pod IP. PID namespaces are not shared by default.'),part('volume','emptyDir volume','Shared storage chest','volume',0x98735c,'The example declares one emptyDir mounted at /shared in both containers.','Files are shared only at the configured mount paths. This is not persistent storage across Pod deletion.')]},
app:{id:'app',name:'Application container',parent:'pod',relations:['Application process → host kernel','Root filesystem is separate from helper root filesystem','/shared → Pod emptyDir volume'],pieces:[part('app-shell','Container shell','Cargo enclosure','container',0xc76b40,'The container environment groups a process and its configured resources.','This is not a virtual machine and has no separate Linux kernel.'),part('app-process','Application process','Work inside cargo','process',0x418e6d,'The application runs as a process. Running does not imply readiness.','The marker is illustrative; no live PID or telemetry is claimed.'),part('app-rootfs','Root filesystem','Image and writable layers','plate',0xc1946d,'The root filesystem combines image-based content and a writable layer.','Volume mounts are separate from the container writable layer.'),part('app-mount','/shared mount','Storage connection','volume',0x98735c,'This path mounts the Pod’s shared emptyDir.','This represents a mount relationship, not another copy of the volume.')]},
helper:{id:'helper',name:'Helper container',parent:'pod',relations:['Helper process → same host kernel','/shared → same Pod emptyDir volume'],pieces:[part('helper-shell','Helper enclosure','Supporting cargo','container',0x358f87,'A second regular container with its own image and process.','Native sidecar lifecycle semantics are not modeled in this example.'),part('helper-process','Helper process','Supporting work','process',0x418e6d,'A process running in the helper container.','It does not share the application’s PID namespace by default.'),part('helper-rootfs','Helper root filesystem','Separate filesystem layers','plate',0x7ca99f,'An independent root filesystem and writable layer.','Only explicit mounts share files with the other container.'),part('helper-mount','/shared mount','Shared storage connection','volume',0x98735c,'Mounts the same emptyDir used by the application container.','This is the same volume, not a second storage chest in the real system.')]},
runtime:{id:'runtime',name:'Runtime internals',parent:'node',relations:['kubelet → CRI → containerd','containerd → shim / OCI runtime → process'],pieces:[part('containerd','containerd','Machinery module','bridge',0xdba025,'Provides runtime services and CRI integration.','CRI is an interface, not an additional container.'),part('shim','Runtime shim','Control module','ledger',0x9c91b5,'Supports runtime lifecycle supervision in this implementation.','Shim cardinality depends on runtime configuration.'),part('runc','runc / OCI runtime','Actuator','crane',0xdba025,'Performs OCI lifecycle operations such as container creation and start.','Do not interpret this as a permanently running engine per container.'),part('images','Image content and snapshots','Supply rack','plate',0xb5976e,'Local content and snapshots provide container filesystem data.','The local image store is distinct from a remote image registry.')]},
linux:{id:'linux',name:'Linux foundation',parent:'node',relations:['Both container processes → one host kernel','Processes have namespace memberships','Cgroups control resource allocation; mounts connect filesystems'],pieces:[part('kernel','Shared host kernel','Foundation','plate',0x8d86af,'Provides system calls and operating-system mechanisms to all processes in this profile.','Not a separate kernel inside each container.'),part('namespaces','Namespaces','Isolation boundaries','plate',0x478fbc,'Network, mount, PID, IPC and UTS memberships isolate or share selected views.','These are boundary diagrams, not physical layers or universally shared Pod resources.'),part('cgroups','Cgroup v2','Resource controls','ledger',0x9b86b5,'Controls and accounts for resources such as CPU and memory.','Requests, limits and measured usage are different; exact hierarchy depends on configuration.'),part('mounts','Mounts and filesystems','Storage relationships','volume',0x98735c,'Mount namespaces connect paths to filesystems and volumes.','A shared volume does not merge entire root filesystems.')]},
harbor:{id:'harbor',name:'Control plane',parent:'fleet',relations:['Controllers and scheduler ↔ API server ↔ etcd','Scheduler assigns nodes; kubelet starts local reconciliation'],pieces:[part('api','API server','Harbor office','bridge',0x779cbb,'Exposes API operations and checks requests before persistence.','Does not synchronously command every lifecycle action.'),part('etcd','etcd','Harbor ledger','ledger',0x9582b5,'Persists API records and revisions.','Does not store application files or container images.'),part('controllers','Controllers','Fleet supervisors','harbor',0x8b8fba,'Independent loops reconcile observed and desired state.','Deployment and ReplicaSet controllers are separate loops.'),part('scheduler','Scheduler','Cargo planner','bridge',0x688db1,'Selects an eligible node and records binding through the API.','Does not start containers or migrate an existing Pod.')]}
};
export function breadcrumbs(id:string):Scope[]{const result:Scope[]=[];let s:Scope|undefined=scopes[id];while(s){result.unshift(s);s=s.parent?scopes[s.parent]:undefined}return result}
export function positionFor(scope:string,index:number,count:number,amount:number):[number,number,number]{
const cols=scope==='fleet'?7:count>4?3:2;const row=Math.floor(index/cols),col=index%cols;const spread:[number,number,number]=[(col-(cols-1)/2)*(scope==='fleet'?5.5:4),0,(row-(Math.ceil(count/cols)-1)/2)*(scope==='fleet'?7:3.5)];
let base:[number,number,number];
if(scope==='fleet'){
const piece=scopes.fleet.pieces[index],source=fleetSources[piece.id];
if(!source)base=[5,0,2];
else if(source.scope==='harbor')base=[(index-1.5)*2.5,0,-5];
else {const group=scopes[source.scope],localIndex=group.pieces.findIndex(p=>p.id===source.id);const local=positionFor(source.scope,localIndex,group.pieces.length,0);const offsets:Record<string,[number,number,number]>={node:[-2,0,1],pod:[-2,1,2.2],app:[-2.8,1.3,2.2],helper:[-1.2,1.3,2.2],runtime:[-.8,1,1],linux:[-2,-1,1]};const offset=offsets[source.scope];base=local.map((v,k)=>v+offset[k]) as [number,number,number];}
}
else if(scope==='node')base=([[0,0,0],[0,1,-1.5],[1.2,1,0],[0,1,1.2],[0,-.5,0]] as [number,number,number][])[index];
else if(scope==='pod')base=([[0,0,0],[-.8,.25,0],[.8,.25,0],[0,-.25,0],[0,-.45,0],[0,.2,1.6]] as [number,number,number][])[index];
else base=[0,index*.38,0];
return base.map((v,k)=>v+(spread[k]-v)*amount) as [number,number,number];}

/** Fleet overview exposes the existing detailed pieces instead of three closed shells.
 * Each source scope retains its own inventory for focused inspection.
 */
export const fleetSources:Record<string,{scope:string;id:string}>={};
const fleetDetails:Piece[]=[];
for(const scopeId of ['harbor','node','pod','app','helper','runtime','linux']){
  for(const piece of scopes[scopeId].pieces){
    // A navigable grouping is replaced by its actual children in the full inventory.
    if(piece.scope)continue;
    const id=scopeId+'/'+piece.id;
    fleetSources[id]={scope:scopeId,id:piece.id};
    fleetDetails.push({...piece,id,name:piece.name,analogy:(scopeId==='harbor'?'Control plane':'Worker-01')+' · '+piece.analogy});
  }
}
fleetDetails.push({...scopes.fleet.pieces[2],id:'worker-02'});
scopes.fleet.pieces=fleetDetails;
scopes.fleet.relations=['Full inventory: control plane and reference worker internals','Select a piece, then Open its level for focused exploration','Worker-02 is contextual; its detailed instance is not modeled'];
