import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {PointerTap} from './pointer-tap';
import {scopes,positionFor,type Piece} from './hierarchy';
type Props={scope:string;selected:string;explode:number;isolated:boolean;dark:boolean;reset:number;onSelect:(id:string)=>void};
export default function HierarchyScene(p:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(p);latest.current=p;const [failed,setFailed]=useState(false);
useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;el.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Explorable model. Drag to orbit and scroll to zoom. The inventory provides keyboard selection.');
const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=120;controls.maxPolarAngle=Math.PI*.48;scene.add(new T.HemisphereLight(0xffffff,0x778a98,2));const sun=new T.DirectionalLight(0xfff8ec,2.5);sun.position.set(-5,10,6);scene.add(sun);const root=new T.Group();scene.add(root);
const mat=(color:number)=>new T.MeshStandardMaterial({color,roughness:.6,metalness:.12});
function box(g:T.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,color:number){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(color));m.position.set(x,y,z);g.add(m);return m}
function cylinder(g:T.Object3D,r:number,h:number,x:number,y:number,z:number,color:number){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,24),mat(color));m.position.set(x,y,z);g.add(m);return m}
function model(piece:Piece){const g=new T.Group();const c=piece.color;
if(piece.shape==='ship'){const shape=new T.Shape();shape.moveTo(-1.5,-2.5);shape.lineTo(1.5,-2.5);shape.lineTo(1.5,1.5);shape.quadraticCurveTo(1.3,2.5,0,3);shape.quadraticCurveTo(-1.3,2.5,-1.5,1.5);shape.closePath();const hull=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.65,bevelEnabled:true,bevelSize:.1,bevelThickness:.1,bevelSegments:3}),mat(c));hull.rotation.x=Math.PI/2;hull.position.y=.65;g.add(hull);box(g,2.75,.1,4.6,0,.7,-.25,0xd7c6a6);for(const side of [-1,1]){for(let z=-2.2;z<1.8;z+=.45)box(g,.035,.4,.035,side*1.35,.96,z,0xe6e6df);box(g,.035,.035,4.2,side*1.35,1.16,-.2,0xe6e6df);for(let z=-1.7;z<1.6;z+=.55){const tire=new T.Mesh(new T.TorusGeometry(.14,.055,8,16),mat(0x343b3f));tire.position.set(side*1.54,.4,z);tire.rotation.y=Math.PI/2;g.add(tire)}}if(p.scope==='fleet'&&piece.id==='worker-02'){box(g,2,1,1.3,0,1.3,-1.5,0xeeeeea);box(g,1.8,.3,.06,0,1.5,-.82,0x417080);box(g,1.5,.8,1.4,0,1.1,.5,0xc76b40)} }
else if(piece.shape==='container'){box(g,1.35,.95,2,0,.5,0,c);for(const side of [-1,1]){for(let z=-.9;z<1;z+=.16)box(g,.045,.8,.03,side*.69,.5,z,0xd4c7b6);box(g,.025,.75,.03,side*.3,.5,1.025,0xd8d6ca)}box(g,1.4,.07,2.06,0,1,0,0xb4b8ac);box(g,.04,.9,.04,0,.5,1.03,0xe8dfca)}
else if(piece.shape==='pod'){box(g,3.3,.13,2.5,0,.05,0,c);for(const x of [-1.62,1.62])for(const z of [-1.22,1.22])box(g,.08,1.4,.08,x,.75,z,c);for(const x of [-1.62,1.62])box(g,.08,.08,2.5,x,1.45,0,c);if(p.scope==='node'){box(g,1.3,.85,1.9,-.75,.55,0,0xc76b40);box(g,1.3,.85,1.9,.75,.55,0,0x358f87)}}
else if(piece.shape==='crane'){box(g,1,.2,1,0,.1,0,c);box(g,.2,2.3,.2,-.35,1.3,0,c);box(g,2.5,.2,.25,.55,2.5,0,c);box(g,.035,1.5,.035,1.6,1.65,0,0x4e5960);const hook=new T.Mesh(new T.TorusGeometry(.14,.045,8,20,Math.PI*1.5),mat(0x4e5960));hook.position.set(1.6,.9,0);g.add(hook);box(g,.6,.7,.7,-.5,.6,0,0xa57929)}
else if(piece.shape==='bridge'||piece.shape==='harbor'){box(g,2,1.1,1.6,0,.6,0,c);box(g,2.2,.15,1.8,0,1.23,0,0xf0eee6);for(let x=-.7;x<.9;x+=.45)box(g,.3,.32,.04,x,.85,.82,0x3c657d);box(g,.45,.6,.05,0,.35,.83,0x5a6f75);box(g,.045,.8,.045,.7,1.65,0,0x657981)}
else if(piece.shape==='ledger'){for(let i=0;i<3;i++){cylinder(g,.7,.25,0,.17+i*.35,0,c);cylinder(g,.72,.04,0,.32+i*.35,0,0xcfc9dd)}}
else if(piece.shape==='volume'){box(g,1.1,.65,.9,0,.35,0,c);box(g,1.18,.09,.98,0,.73,0,0xc8a376);for(const x of [-.4,.4])box(g,.06,.7,.95,x,.4,0,0x536571)}
else if(piece.shape==='process'){cylinder(g,.42,.7,0,.4,0,c);const ring=new T.Mesh(new T.TorusGeometry(.52,.04,8,32),mat(0x6b9a87));ring.rotation.x=Math.PI/2;ring.position.y=.13;g.add(ring)}
else{for(let i=0;i<3;i++)box(g,2,.08,1.5,0,i*.15,0,i===1?0xdce0de:c)}return g}
const entries=scopes[p.scope].pieces.map(piece=>{const group=model(piece);group.userData.id=piece.id;root.add(group);const label=document.createElement('button');label.className='part-label';label.textContent=piece.name;label.onclick=()=>latest.current.onSelect(piece.id);el.append(label);return{piece,group,label}});
const canvas=renderer.domElement,tap=new PointerTap(),ray=new T.Raycaster(),pointer=new T.Vector2();const down=(e:PointerEvent)=>tap.down(e.pointerId,e.clientX,e.clientY,8),move=(e:PointerEvent)=>tap.move(e.pointerId,e.clientX,e.clientY),cancel=(e:PointerEvent)=>tap.cancel(e.pointerId),up=(e:PointerEvent)=>{if(!tap.up(e.pointerId,e.clientX,e.clientY))return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(entries.filter(e=>e.group.visible).map(e=>e.group),true)[0];if(hit){let o:T.Object3D|null=hit.object;while(o&&!o.userData.id)o=o.parent;if(o)latest.current.onSelect(o.userData.id)}};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);
let frame=0,key='';function fit(){const b=new T.Box3();entries.filter(e=>e.group.visible).forEach(e=>{b.expandByObject(e.group);if(!latest.current.isolated){const previous=e.group.position.clone();const i=entries.indexOf(e);e.group.position.set(...positionFor(p.scope,i,entries.length,1));e.group.updateMatrixWorld(true);b.expandByObject(e.group);e.group.position.copy(previous);e.group.updateMatrixWorld(true)}});if(b.isEmpty())return;const size=b.getSize(new T.Vector3()),center=b.getCenter(new T.Vector3());const distance=p.scope==='fleet'?Math.max(size.x/Math.max(.5,camera.aspect),size.z)*1.65:Math.max(size.length()*.85,Math.max(size.x/Math.max(.5,camera.aspect),size.y)*1.5,4);controls.target.copy(center);camera.position.copy(center).add((p.scope==='fleet'?new T.Vector3(.03,1,.25):new T.Vector3(.38,.75,1)).normalize().multiplyScalar(distance*(p.scope==='fleet'?1:1.45)));controls.update()}
const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);key=''};const ro=new ResizeObserver(resize);ro.observe(el);resize();function draw(){frame=requestAnimationFrame(draw);const v=latest.current;entries.forEach((e,i)=>{e.group.position.set(...positionFor(p.scope,i,entries.length,v.explode));e.group.visible=!v.isolated||e.piece.id===v.selected;e.group.traverse(o=>{if(o instanceof T.Mesh){const m=o.material as T.MeshStandardMaterial;m.emissive.set(e.piece.id===v.selected?0x285b61:0);m.emissiveIntensity=.18}})});const next=v.reset+':'+v.isolated+':'+(v.isolated?v.selected:'');if(key!==next){fit();key=next}controls.update();const placed:{x:number;y:number;w:number}[]=[];entries.forEach((e,entryIndex)=>{e.label.setAttribute('aria-label',e.piece.name);e.label.title=e.piece.name;e.label.textContent=p.scope==='fleet'&&e.piece.id!==v.selected?String(entryIndex+1).padStart(2,'0'):e.piece.name;e.label.hidden=!e.group.visible||(p.scope==='fleet'&&v.explode<.35&&e.piece.id!==v.selected);e.label.setAttribute('aria-pressed',String(e.piece.id===v.selected));if(e.label.hidden)return;const b=new T.Box3().setFromObject(e.group),pt=b.getCenter(new T.Vector3());pt.y=b.max.y+.3;pt.project(camera);let x=(pt.x+1)*el.clientWidth/2,y=(1-pt.y)*el.clientHeight/2;const w=e.label.offsetWidth;x=Math.max(w/2+3,Math.min(el.clientWidth-w/2-3,x));for(let j=0;j<10&&placed.some(t=>Math.abs(t.x-x)<(t.w+w)/2+4&&Math.abs(t.y-y)<29);j++)y+=30;e.label.style.left=x+'px';e.label.style.top=Math.min(el.clientHeight-20,Math.max(15,y))+'px';placed.push({x,y,w})});renderer.toneMappingExposure=v.dark?.8:1;renderer.render(scene,camera)}draw();return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);root.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(o.material as T.Material).dispose()}});entries.forEach(e=>e.label.remove());renderer.dispose();canvas.remove()};},[p.scope]);
return <div className="hierarchy-scene" ref={host}>{failed&&<p role="alert">WebGL is unavailable. Use the inventory and descriptions to explore.</p>}</div>}
