import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {PointerTap} from './pointer-tap';
import {components,maritime,type ComponentId,type Layer} from './scenario';
type Props={dark:boolean;analogy:boolean;selected:ComponentId;active:ComponentId;visible:Layer[];isolate:boolean;explode:number;reset:number;running:boolean;onSelect:(id:ComponentId)=>void};
export default function Scene(props:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const [error,setError]=useState('');
useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch{setError('3D is unavailable. Use the component list and guided scenario to explore.');return}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive Kubernetes harbor. Ships represent worker nodes. Drag to orbit, scroll to zoom or select a labeled structure.');const scene=new T.Scene(),camera=new T.PerspectiveCamera(36,1,.1,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=38;controls.maxPolarAngle=Math.PI/2.1;const home=()=>{camera.position.set(7,10,14);controls.target.set(0,.6,0)};home();
scene.add(new T.HemisphereLight(0xffffff,0x89989a,1.7));const sun=new T.DirectionalLight(0xfffcf2,2.1);sun.position.set(-5,12,7);scene.add(sun);
const groups:T.Group[]=[],scenery=new T.Group();scene.add(scenery);const labels:{el:HTMLDivElement;position:T.Vector3;id?:ComponentId;group?:T.Group}[]=[];
const label=(text:string,position:T.Vector3,id?:ComponentId,group?:T.Group)=>{const div=document.createElement('div');div.className='scene-label';div.textContent=text;el.append(div);labels.push({el:div,position,id,group})};
function box(parent:T.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,color:number){const m=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.72,metalness:.04}));m.position.set(x,y,z);parent.add(m);return m}
function cylinder(parent:T.Object3D,r:number,h:number,x:number,y:number,z:number,color:number){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,24),new T.MeshStandardMaterial({color,roughness:.65}));m.position.set(x,y,z);parent.add(m);return m}
// A calm, bounded water surface keeps the metaphor readable as a model.
const water=new T.Mesh(new T.CircleGeometry(8.4,96),new T.MeshStandardMaterial({color:0xa7d2dc,roughness:.65,metalness:.1,transparent:true,opacity:.72}));water.rotation.x=-Math.PI/2;water.position.y=-.25;scenery.add(water);
box(scenery,10,.32,2.9,0,0,-3.6,0xd5d1c6);box(scenery,.6,.16,6.5,0,-.02,.3,0xd0c8b8);
for(let x=-4.4;x<=4.4;x+=1.1)cylinder(scenery,.08,.3,x,.3,-2.35,0x657879);
function boat(x:number,z:number,color:number){const boat=new T.Group();boat.position.set(x,0,z);scenery.add(boat);const shape=new T.Shape();shape.moveTo(-1.5,-2.2);shape.lineTo(1.5,-2.2);shape.lineTo(1.5,1.6);shape.lineTo(.7,2.35);shape.lineTo(0,2.65);shape.lineTo(-.7,2.35);shape.lineTo(-1.5,1.6);shape.closePath();const hull=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.65,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.12,bevelThickness:.1}),new T.MeshStandardMaterial({color,roughness:.7}));hull.rotation.x=-Math.PI/2;hull.position.y=-.05;boat.add(hull);box(boat,2.65,.12,3.7,0,.66,-.1,0xe1d7c3);for(const side of [-1,1]){box(boat,.06,.14,3.8,side*1.35,.84,-.1,0xf5f2e9);for(let n=-1.7;n<1.7;n+=.55)box(boat,.05,.35,.05,side*1.35,.88,n,0xf5f2e9)}return boat}
boat(-2.5,.65,0x205c87);const idle=boat(2.5,.65,0x238980);box(idle,1.8,.75,1,0,1.1,-1.45,0xf1ede3);box(idle,1.5,.28,.08,0,1.22,-.91,0x647b85);box(idle,.85,.55,1.15,0,.98,.1,0xba704e);
label('CAPITAINERIE',new T.Vector3(0,.3,-5.35));label('SHIP 01 · worker-01',new T.Vector3(-2.5,.7,3.85));label('SHIP 02 · worker-02',new T.Vector3(2.5,.7,3.85));
const positions:Record<ComponentId,[number,number,number]>={api:[-3.6,.2,-3.6],etcd:[-1.3,.2,-3.6],controllers:[1.1,.2,-3.6],scheduler:[3.5,.2,-3.6],kubelet:[-2.5,.72,-.9],runtime:[-2.5,.72,.55],process:[-2.5,.72,2]};
components.forEach(c=>{const g=new T.Group();g.position.set(...positions[c.id]);g.userData={id:c.id,base:g.position.clone(),layer:c.layer};scene.add(g);groups.push(g);
if(c.id==='etcd'){for(let i=0;i<3;i++){cylinder(g,.52,.28,0,.2+i*.34,0,0x9582b5);cylinder(g,.54,.04,0,.36+i*.34,0,0xdde2d5)}}
else if(c.id==='runtime'){box(g,.5,.15,.8,0,.1,0,0xe6a632);box(g,.13,1.45,.13,-.35,.8,0,0xe6a632);box(g,1.65,.13,.16,.38,1.52,0,0xe6a632);box(g,.025,.62,.025,1.05,1.16,0,0x647077);box(g,.19,.1,.12,1.05,.81,0,0x647077)}
else if(c.id==='process'){box(g,1.85,.09,1.22,0,.06,0,0xb6bbae);const cargo=box(g,1.5,.75,1,0,.49,0,0xcb7045);cargo.userData.cargo=true;for(let i=-.6;i<=.61;i+=.2)box(g,.035,.64,.04,i,.5,.52,0xf2bf8b);box(g,.5,.18,.06,0,.51,.56,0x536d60)}
else{const col=c.id==='api'?0x779cbb:c.id==='scheduler'?0x688db1:c.id==='kubelet'?0x6baba5:0x8b8fba;box(g,1.6,c.id==='kubelet'?.75:1.05,1.25,0,.54,0,col);box(g,1.78,.13,1.4,0,1.13,0,0xeae7df);for(const x of [-.45,0,.45])box(g,.27,.25,.04,x,.75,.65,0x637f8c);if(c.id==='api'){box(g,.35,.48,.05,0,.32,.65,0x716e61)}if(c.id==='scheduler'){box(g,.05,.8,.05,0,1.6,0,0x6a787a);box(g,.44,.25,.035,.2,1.85,0,0x67989a)}}
label(c.name,new T.Vector3(0,c.id==='runtime'?2:1.5,0),c.id,g)});
const tap=new PointerTap(),ray=new T.Raycaster(),pointer=new T.Vector2();const down=(e:PointerEvent)=>tap.down(e.pointerId,e.clientX,e.clientY,e.pointerType==='touch'?12:5),move=(e:PointerEvent)=>tap.move(e.pointerId,e.clientX,e.clientY),cancel=(e:PointerEvent)=>tap.cancel(e.pointerId),up=(e:PointerEvent)=>{if(!tap.up(e.pointerId,e.clientX,e.clientY))return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(groups.filter(g=>g.visible),true)[0];if(hit){let o:T.Object3D|null=hit.object;while(o&&!o.userData.id)o=o.parent;if(o)latest.current.onSelect(o.userData.id)}};
const canvas=renderer.domElement;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};const ro=new ResizeObserver(resize);ro.observe(el);resize();let frame=0,lastReset=-1;
const draw=()=>{frame=requestAnimationFrame(draw);const p=latest.current;if(p.reset!==lastReset){home();lastReset=p.reset}renderer.toneMappingExposure=p.dark?.8:1.0;water.material.color.set(p.dark?0x244f65:0xa7d2dc);scenery.visible=!p.isolate;groups.forEach(g=>{g.visible=p.visible.includes(g.userData.layer)&&(!p.isolate||g.userData.id===p.selected);g.position.copy(g.userData.base);g.position.y+=p.explode*(g.userData.layer==='linux'?2.5:g.userData.layer==='node'?1.5:.8);g.traverse(o=>{if(o instanceof T.Mesh){const m=o.material as T.MeshStandardMaterial;m.emissive.set(g.userData.id===p.selected?0x326e70:0);m.emissiveIntensity=.2;m.transparent=g.userData.id==='process'&&!p.running;m.opacity=m.transparent?.32:1}})});controls.update();const occupied:{x:number;y:number;w:number;h:number}[]=[];labels.forEach(l=>{const v=l.group?l.group.position.clone().add(l.position):l.position.clone();v.project(camera);l.el.hidden=(l.group?!l.group.visible:p.isolate)||(!!l.id&&l.id!==p.selected&&l.id!==p.active)||v.z>1||v.z< -1;l.el.textContent=l.id?(p.analogy?maritime[l.id].name+' · '+components.find(c=>c.id===l.id)!.name:components.find(c=>c.id===l.id)!.name):l.el.textContent;if(!l.id&&l.el.textContent==='CAPITAINERIE')l.el.textContent='HARBOR · control plane';let x=(v.x+1)*el.clientWidth/2,y=(-v.y+1)*el.clientHeight/2;if(!l.el.hidden){const w=l.el.offsetWidth,h=l.el.offsetHeight;x=Math.max(w/2+3,Math.min(el.clientWidth-w/2-3,x));for(let i=0;i<12&&occupied.some(o=>Math.abs(x-o.x)<(w+o.w)/2+4&&Math.abs(y-o.y)<(h+o.h)/2+4);i++)y+=h+4;y=Math.min(el.clientHeight-h/2-4,y);occupied.push({x,y,w,h})}l.el.style.left=x+'px';l.el.style.top=y+'px';l.el.classList.toggle('selected',l.id===p.selected);l.el.classList.toggle('active',l.id===p.active)});renderer.render(scene,camera)};draw();
return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});labels.forEach(l=>l.el.remove());renderer.dispose();canvas.remove()};},[]);
return <div className="scene" ref={host}>{error&&<p className="scene-error" role="alert">{error}</p>}</div>}
