import {test} from 'node:test';import assert from 'node:assert/strict';import {components,creation,replacement,move} from './scenario.ts';import {PointerTap} from './pointer-tap.ts';
test('every scenario actor resolves and readiness follows process start',()=>{for(const steps of [creation,replacement])for(const step of steps){assert.ok(components.some(c=>c.id===step.actor));assert.ok(!step.ready||step.process)}assert.equal(creation[4].process,false);assert.equal(creation.at(-1)?.ready,true);assert.match(replacement.at(-1)!.objects,/Pod B/)});
test('timeline navigation clamps at both boundaries',()=>{assert.equal(move(0,-1,9),0);assert.equal(move(8,1,9),8);assert.equal(move(4,-1,9),3)});
test('drag and multitouch never select a component',()=>{const t=new PointerTap();t.down(1,0,0,5);t.move(1,20,0);assert.equal(t.up(1,0,0),false);t.down(1,0,0,5);t.down(2,0,0,5);assert.equal(t.up(2,0,0),false);assert.equal(t.up(1,0,0),false);t.down(1,0,0,5);assert.equal(t.up(1,1,1),true)});

import {scopes,breadcrumbs,positionFor} from './hierarchy.ts';
test('all hierarchy scopes resolve and have acyclic parent paths',()=>{for(const s of Object.values(scopes)){assert.ok(s.pieces.length);assert.equal(new Set(s.pieces.map(p=>p.id)).size,s.pieces.length);for(const p of s.pieces)if(p.scope)assert.ok(scopes[p.scope]);const path=breadcrumbs(s.id);assert.equal(path[0].id,'fleet');assert.equal(new Set(path.map(p=>p.id)).size,path.length)}});
test('reference Pod has two distinct containers and one shared volume',()=>{const pieces=scopes.pod.pieces;assert.equal(pieces.filter(p=>p.shape==='container').length,2);assert.equal(pieces.filter(p=>p.id==='volume').length,1);assert.equal(scopes.app.parent,'pod');assert.equal(scopes.helper.parent,'pod')});
test('full explosion gives every sibling a unique finite position',()=>{for(const s of Object.values(scopes)){const positions=s.pieces.map((_,i)=>positionFor(s.id,i,s.pieces.length,1));assert.ok(positions.flat().every(Number.isFinite));assert.equal(new Set(positions.map(p=>p.join(','))).size,positions.length)}});

test('fleet explosion exposes detailed components, not three opaque groups',()=>{const ids=new Set(scopes.fleet.pieces.map(p=>p.id));assert.ok(ids.size>20);for(const id of ['harbor/api','node/kubelet','runtime/containerd','app/app-process','pod/volume'])assert.ok(ids.has(id),id);assert.ok(!ids.has('harbor'));});
test('fleet parts move materially between assembled and exploded positions',()=>{const s=scopes.fleet;let moved=0;for(let i=0;i<s.pieces.length;i++){const a=positionFor('fleet',i,s.pieces.length,0),b=positionFor('fleet',i,s.pieces.length,1);if(Math.hypot(...a.map((v,k)=>v-b[k]))>2)moved++}assert.ok(moved>s.pieces.length*.8)});
